apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpsserver-istio
spec:
  gateways:
    - httpsserver-istio
  hosts:
    - httpsserver-istio.cncamp.io
  http:
    - match:
        - uri:
            exact: "/isto/metrics"
      rewrite:
        uri: "/metrics"
      route:
        - destination:
            host: httpserver-istio.module12.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            exact: "/httpserver"
      rewrite:
        uri: "/healthz"
      route:
        - destination:
            host: httpserver-istio.module12.svc.cluster.local
            port:
              number: 80
    - match:
        - port: 443
      route:
        - destination:
            host: httpserver-istio.module12.svc.cluster.local
            port:
              number: 80


---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: httpsserver-istio
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - httpsserver-istio.cncamp.io
      port:
        name: https-default
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: cncamp-credential